INSERT INTO USERS VALUES ('123', '123', '박선진');
INSERT INTO USERS VALUES ('1234', '1234', '정석현');

INSERT INTO CINEMA VALUES (1, 'CGV용산아이파크몰', '01', '0013');

INSERT INTO HALLTYPE VALUES (1, 1, '2D');
INSERT INTO HALLTYPE VALUES (2, 1, '4D');
INSERT INTO HALLTYPE VALUES (3, 1, 'IMAX');

INSERT INTO MOVIE VALUES (1, '스파이더맨-노 웨이 홈');
INSERT INTO MOVIE VALUES (2, '유체이탈자');
INSERT INTO MOVIE VALUES (3, '연애 빠진 로맨스');